on:
  pull_request:
    branches:
      - main
name:  ğŸ” Check Linting
jobs:
  lint-frontend:
    name: ğŸ” Run linters
    runs-on: ubuntu-latest
        
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v3.5.3
        
      - name: âš™ Set Node.js 19.x
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 19.x

      - name: ğŸˆ yarn install
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: install

      - name: Run linters
        uses: Borales/actions-yarn@v4.2.0
        with:
          eslint: true
          eslint_args: "--max-warnings 0"
          eslint_dir: "client"
