on:
  pull_request:
    branches:
      - main
    paths:
      - "contracts/**"

name:  ðŸ”Ž Scarb checks
jobs:
  scarb-checks:
    name: ðŸ”Ž Scarb checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v3.5.3

      - name: âš™ Set scarb
        uses: software-mansion/setup-scarb@v1.0.1
        with:
          scarb-version: "0.6.0-alpha.0"
      
      - name: ðŸ”Ž Check fmt
        run: scarb fmt --check

      - name: ðŸ”Ž Run tests
        run: scarb test
